### PR TITLE
Add a 'sort all' option to the sort select menu

### PR DESCRIPTION
**Pull request by pjrobertson**
In the 'sort' tab, there is now an option to 'sort all'. When 'ok' is clicked, javascript is run that finds the min/max cols/rows and selects them as the data range for sorting.

I've also done a bit more tidying up.

### CODE REVIEW

**Comment by pjrobertson** [comment]
For now I've reverted the commit that made those changes. I'll look into cleaning it up when I better understand it all!

**Comment by pjrobertson** [comment]
@audreyt I've reverted that commit. Can this be merged?

**Comment by audreyt** [comment]
Merged. Thanks! :rainbow:

**Comment by pjrobertson** [comment]
Cool, I want to get to work on a few more things!

* filter option
* improve sort further to not sort header rows
* allow filtering/sorting without altering the original sheet

**Pull request merged**
