### PR TITLE
Add wildcard/single char matching for COUNTIF

### LINKED ISSUE #228: countif wildcard support
`COUNTIF(range,criteria)` supports, both in google docs and Execl, pattern matching on string criteria. For example, `"*"` means "zero or more contigous characters" and `"?"` means "any single character". To match `"*"` or `"?"`, one uses `"~*"` and `"~?"`.

It would be nice to have that supported as well!

### PR DESCRIPTION
**Pull request by pjrobertson**
Fixes #228

This adds the ability to use * and ? in the COUNTIF (and similar) functions. I used the exact criteria as defined in #228

### CODE REVIEW

**Comment by audreyt** [comment]
Awesome, thanks! :rainbow:

**Comment by pjrobertson** [comment]
FYI - I didn't update the compiled binaries. I will let you do that before you merge :-)
(I wasn't sure which files needed re-saving)

Please don't merge just quite yet, I'm still checking one small thing

**Comment by pjrobertson** [comment]
@audreyt - I've added another commit. Feel free to take a look and check to make sure it works!

谢谢`

**Comment by audreyt** [comment]
I've merged it literally a minute after your commit. :-)

**Pull request merged**
