### PR TITLE
Update Sandstorm build (WIP)

### PR DESCRIPTION
**Pull request by ocdtrekkie**
This PR (so far) appears to work. It is hard to see what is or isn't changed out in sandstorm-files.list since there are so many, more testing should be done yet in `spk dev` to make sure dependencies for all possible features are included. I also have not bumped forward the Sandstorm metadata yet.

I didn't know how to do the CoffeeScript stuff, so merge conflicts were done manually in both the LS and JS files, which is why there's a commit to remove an errant bracket in the JS. I hope that's the only error, but it "seems to work".

So far I created a new test file and an restored a grain from the old version of EtherCalc. (The main difference is dump.json being replaced by /dump. It looks like the grain backup keeps the dump.json but successfully imports it over to /dump as well, which seems like a reasonable import strategy.)

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
As an additional note, I was curious @audreyt if there was any particular opinion you had on the Sandstorm build was maintained as a separate branch other than that it originated from being my fork/branch. While it would be a bit of a pain to go and manually re-adjust things, a "better" way to do this would likely be to reimplement the Sandstorm changes based on a SANDSTORM=1 environment variable, which is a common strategy in newer Sandstorm apps, and PR those changes directly into master. If it was brought into master, we would no longer need to handle the merge conflict process for Sandstorm builds.

**Comment by audreyt** [comment]
Thanks for the contribution! I do agree that a `master` approach based on environment probing is better.

**Comment by ocdtrekkie** [comment]
Alright, for now I will work on this branch, and do some more testing, so we're confident current EtherCalc on Sandstorm works with the existing strategy, and then I'll start looking into integrating the changes better in future adjustments.

**Comment by ocdtrekkie** [comment]
Heh, that's what I get for writing a commit message before seeing what it actually added. ><

I may have found an issue with imported data, it doesn't seem like it's saving it somewhere it can find it later.

**Comment by ocdtrekkie** [comment]
@audreyt My inclination is that this build probably is fine. I'm not sure what version number you'd want to attach to it, but could you bump the versions in the package definition and submit it to the market when you have time? We can leave it in the experimental market (a.k.a. unapproved) until a few people test it.

**Comment by audreyt** [comment]
OK. One quedstion — is the experimental market link still https://apps.sandstorm.io/?experimental=true ? I tried loading it on a few browsers and they all stuck in "Loading..." screen. 

(Perhaps it's because https://app-index.sandstorm.io/experimental/index.json is an empty array?)

**Comment by ocdtrekkie** [comment]
Yes. When there's no pending apps it just stays at Loading…

Sent from my Windows 10 phone

**Comment by fbender** [comment]
What's the forward plan here? @ocdtrekkie @audreyt

**Comment by ocdtrekkie** [comment]
I haven't looked at this in a while, but AFAIK this PR works.

**Pull request merged**
