### PR TITLE
Small UI and dependency changes

### PR DESCRIPTION
**Pull request by pjrobertson**
I've changed some of the tooltips to make it clearer to first time users what each of the buttons do.
In reality, I would like to change the icons to something like the ones in font-awesome (the current ones are quite ugly)

I also had a problem uploading an xls sheet to Ethercalc - it was a problem with xlsx.js - so I've updated that (and jszip)

### CODE REVIEW

**Comment by audreyt** [comment]
Awesome, thanks! :rainbow:

**Comment by audreyt** [comment]
Yeah the icons were hand-drawn bitmaps from Dan Bricklin's original SocialCalc. Changing them to FontAwesome (or GlyphIcons, or Material Icons, etc.) would be great as long as the new icon set remains somewhat consistent.

**Comment by ocdtrekkie** [comment]
FontAwesome looks really cool. (I personally beg people to avoid putting Google icons on literally everything.)

**Comment by pjrobertson** [comment]
OK, I will look into it for another PR. I don't want to hold this PR up :-)
The only other option I have thought of is to use icons from LibreOffice's Calc program (unfortunately not all icons that we'd need exist in FontAwesome - e.g. merge and insert row)
Here's where we could get the icons: https://github.com/LibreOffice/core/tree/master/icon-themes/oxygen/cmd

An example of one (merge cells) is here: 
https://github.com/LibreOffice/core/blob/master/icon-themes/oxygen/cmd/lc_mergecells.png

**Comment by pjrobertson** [comment]
With FontAwesome, I could only find these icons:
calc

**Comment by audreyt** [comment]
There is also the Noun Project. (I personally have no issues mixing icons from multiple sources; the Editor icons from https://google.github.io/material-design-icons/ looks pretty good.)

**Comment by ocdtrekkie** [comment]
Noun Project icons are a good source, though your credits list bloats fast that way. If you use Noun Project, you probably want to ensure all icons are monochrome at the least.

**Comment by audreyt** [comment]
The credit list is already pretty long — https://github.com/audreyt/ethercalc#licensing — I have no problem doubling or tripling its size. :-) Agreed on monochrome icons.

**Pull request merged**
