### PR TITLE
Prevent crash "TypeError: Cannot read property 'exportCSV' of undefined"

### PR DESCRIPTION
**Pull request by ldidry**

### CODE REVIEW

**Comment by eddyparkinson** [comment]
Sorry, this looks like the auto generated file main.js. please change src/main.ls

https://github.com/audreyt/ethercalc/blob/master/src/main.ls#L110
csv <~ SC[room].exportCSV

If I remember the syntax, you can swap the dot for a ! and it will skip the section if it is undefined.
see http://livescript.net/

**Comment by ldidry** [comment]
Thx, I'll check that tomorrow.

**Comment by ldidry** [comment]
How do I regenerate the `main.js` file after my change?

**Comment by ldidry** [comment]
I did `lsc -cp src/main.ls > main.js`.

**Comment by eddyparkinson** [comment]
I see this returns null rather than:

        @response.type Text
        @response.send 404 ''

happy to merge if has been tested, but looks like it might fail.

Sorry I have not used livescript very much, maybe an if would be simpler.

**Comment by ldidry** [comment]
Is it better?

**Pull request merged**
