### PR TITLE
Add startup scripts

### PR DESCRIPTION
**Pull request by rugk**
Taken from Etherpad

This allows you to:
* restart automatically when Ethercalc crashes (`safeRun.sh`)
* add a log file for Ethercalc (`safeRun.sh /path/to/my/logfile.log`)
* send logs via mail when restarts occur (not tested, but it says this in the script)

**Edit:** Fixes https://github.com/audreyt/ethercalc/issues/348 now, too.

### CODE REVIEW

**Comment by eddyparkinson** [comment]
This is a good addition.
Cycle issue - single thread only.There is a cycle issue, if it runs on a single thread - if a change to the spreadsheet state causes and error then this will cycle as the change to the state has been saved already.  
I have started work on a fix, as I have seen this cause a crash twice. 
---
Eddy Parkinson PhD
Software Engineering 

New ideas pass through three periods: 1) It can`t be done. 2) It 
probably can be done, but it`s not worth doing. 3) I knew it was a good 
idea all along! - Arthur C. Clarke
 

    On Wednesday, 18 May 2016, 3:39, rugk <notifications@github.com> wrote:
 

 Taken from EtherpadThis allows you to:   
   - restart automatically when Ethercalc crashes (safeRun.sh)
   - add a log file for Ethercalc (safeRun.sh /path/to/my/logfile.log)
   - send logs via mail when restarts occur (not tested, but it says this in the script)

You can view, comment on, or merge this pull request online at:
  https://github.com/audreyt/ethercalc/pull/347
Commit Summary
   
   - Add Etherpad license
   - Create run.sh
   - Update run.sh
   - Create runSafe.sh
   - run.sh: Activate change dir
   - runSafe.sh: Activate change dir
   - Pass parameters correctly
   - Pass parameters correctly

File Changes
   
   -  M LICENSE.txt (234) 
   -  A bin/run.sh (38) 
   -  A bin/runSafe.sh (69) 

Patch Links:
   
   - https://github.com/audreyt/ethercalc/pull/347.patch
   - https://github.com/audreyt/ethercalc/pull/347.diff

**Comment by rugk** [comment]
So this cycle issue has to be fixed in the "other" part of Ethercalc source code AFAIK?

**Comment by rugk** [comment]
Included now some useful environment variables, which I got from some issues. :smiley:

**Comment by eddyparkinson** [comment]
>So this cycle issue has to be fixed in the "other" part of Ethercalc
Yes - the sheet data would need to be fixed.

**Pull request merged**
