### PR TITLE
New Feature: Package pane functions become a command (pane) and implement snapshot saved.

### PR DESCRIPTION
**Pull request by samejack**

### CODE REVIEW

**Comment by audreyt** [comment]
Wow, awesome! :fireworks: LGTM, I'll review it later tonight for merging.

**Comment by audreyt** [comment]
Hi @samejack , sorry for the revert — it seems with this change, loading an existing spreadsheet, insert a new row and pasting some text will clear the spreadsheet. Would you like to see if you can reproduce this error?

**Comment by samejack** [comment]
I'll check tomorrow, thanks.

**Comment by samejack** [comment]
Hello @audreyt, i have fixed this issue. How do i create Pull Request !? Thanks.

**Comment by audreyt** [comment]
That's OK, I have manually applied the fix. I'll test it more locally and make a release in a few days. Thanks for the prompt fix!

**Comment by samejack** [comment]
Thank you.

**Pull request merged**
