### PR TITLE
add snapcraft.yaml file

### PR DESCRIPTION
**Pull request by dholbach**
In the last days I created a snap of `ethercalc` and this PR contains the `snapcraft.yaml` that's required to build it. I tested it to some degree, but to make sure it's working well enough to be published and distributed to users I need your help.

I'd love to hear if you are generally interested in your software being available as a snap and if you could imagine shipping the `snapcraft.yaml` file in your source repository for easier publishing.

### Background info
If you haven't heard of snaps yet, they are self-contained apps, which can be used on a [multitude of Linux systems](https://snapcraft.io). Via `seccomp`, `apparmor` and other Linux security features, they provide great security for users, uploads to the store are available within seconds and you have
full control over your relevant stack.

Snaps can be installed by millions of users: Ubuntu 16.04 LTS and later have `snapd` installed by default and many other Linux distributions, like Arch, Debian, Gentoo, Fedora, openSUSE, OpenEmbedded, Yocto and OpenWRT made `snapd` (which powers the snap experience) available as well.

### Publishing
Uploading to the store can be done via the command line and there are multiple release channels available, so users can choose between for example stable, beta and alpha releases. You could even hook up `snapcraft upload` with Travis to auto-publish release tags or nightly builds. The process for this is very simple:

 - Once:
  - Register an account at http://myapps.developer.ubuntu.com/
  - Run `snapcraft login`
  - Run `snapcraft register ethercalc`
 - `snapcraft push ethercalc_<version>.snap --release=beta`

### CODE REVIEW

**Comment by eddyparkinson** [comment]
>I tested it to some degree, but to make sure it's working well enough to be published and distributed to users I need your help

What help do you need?  Happy to merge this in if it works.

**Comment by dholbach** [comment]
Happy to get it merged then!

Would you be interested in pushing it to the snap store too? If you are, let's chat and I can help and answers questions.

**Comment by eddyparkinson** [comment]
@dholbach as long the the licenses are ok, then AFAIK it is ok to add to the snap store.  https://github.com/audreyt/ethercalc/blob/master/LICENSE.txt

**Comment by dholbach** [comment]
Thanks a bunch for merging!

Yes, you can pick the license when registering the snap. Are you interested in doing that? I could help you get set up and even hook up CI to publish builds.

**Comment by eddyparkinson** [comment]
Pull requests are welcome. 

We don't have integration tests - so might cause issues with CI.

**Comment by dholbach** [comment]
Shall we start the discussion about CI and publishing in a separate github issue? https://lists.ubuntu.com/archives/snapcraft/2016-August/000831.html might be useful for starting this.

**Comment by eddyparkinson** [comment]
Feel free to open an issue. Will support anyone who wants to work on this.

**Comment by dholbach** [comment]
Thanks a lot. I filed https://github.com/audreyt/ethercalc/issues/449 for this.

**Pull request merged**
