### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by pjrobertson**
I've given ethercalc a fresh lick of paint :-)

Here's what I've done

* Taken the monochrom icons from [LibreOffice](https://github.com/LibreOffice/core/tree/master/icon-themes/sifr/cmd)
* Changed the colours a little
* Got rid of (commented out) some of the move paste/move from/move insert icons. I'm not sure what these commands do? Also, I couldn't find any suitable icons (presumably as I didn't know what they do)
* Made the merge/unmerge buttons into 1. It seems that the 'merge' button also unmerges cells, so there's no need for both of them

Let me know if anything else needs doing

### CODE REVIEW

**Comment by audreyt** [comment]
Awesome, thanks!!

Please see https://workmate.southeasternrailway.co.uk/help-en/SocialCalc%20-%20Move%20Source%20example for the Move semantics. I'd like to keep them in (perhaps with better UI, but original icons would do) if possible.

**Comment by ocdtrekkie** [comment]
Random convenience question: @pjrobertson Can you include a screenshot on UI update PRs in the comments?

I'm wondering if we could maybe do a simple modification of some of the LibreOffice icons to make the missing icons.

**Comment by pjrobertson** [comment]
etghercalc

**Comment by audreyt** [comment]
Merged as of b1a1b67. Thanks so much! :rainbow:

**Comment by ocdtrekkie** [comment]
Very nice. I see we got the missing icons back in too. (They might be a little thin-lined to match the style, but that's not a big issue.)

@audreyt Can we get an updated Sandstorm version after these changes?

**Comment by audreyt** [comment]
Yes, I plan to work on #188 and then roll a Sandstorm version.

**Comment by pjrobertson** [comment]
Cool, nice work @audreyt  :-)

**Pull request merged**
