### PR TITLE
fix tabs disappearing and tabs rename issues in multi sheet - fixes #635

### LINKED ISSUE #635: Multi sheets tabs disappears when rename one of them
Hi,
When I create multi sheets and rename one of the sheet all other sheets disappears.

### PR DESCRIPTION
**Pull request by khawarjatoi**
- Creates snapshot when Sheet1 is created and stores sheet link in it.
- Makes sure sheet name is returned

### CODE REVIEW

**Comment by eddyparkinson** [comment]
Thanks for the edits. You look to have change auto generated code, hope this helps:

Auto generated code
---
/main.js is created from /src/main.ls

static/multi.js looks to be created from  these  https://github.com/audreyt/ethercalc/tree/master/multi

I am not sure about multi, I have never compiled this part of the code.


Change 1 to 2?
---

With the change to /main.js:

Change 1 to 2? on this line, looks like you would get the same result:
https://github.com/audreyt/ethercalc/blob/master/src/main.ls#L408


Live Script
---

When you see auto generated code, I suggest you search for the *.ls source file, i.e. the Live Script
 version.

**Comment by khawarjatoi** [comment]
Thanks for help, I have updated src/main.ls file and tried to compile it locally, main.js file is same. 
### Change 1 to 2? 
When getting sheet links from snapshot it skips first row and starts reading from row 2.

**Comment by khawarjatoi** [comment]
Thanks for help, I have updated src/main.ls file and tried to compile it locally, /main.js file is same.

**Change 1 to 2?**
Because when getting sheet links from snapshot it skips first row and starts reading from row 2.

**static/multi.js**
This file is created from https://github.com/audreyt/ethercalc/tree/master/multi as you have suggested above. I have updated
https://github.com/khawarjatoi/ethercalc/blob/master/multi/foldr.ls 
to fix the issue. But I don't know how to compile and compress all files from multi directory into one static/multi.js file.

**Comment by khawarjatoi** [comment]
I have figured out how to compile multi directory. now it's ready.

**Comment by liudvikaris** [comment]
Hi, @eddyparkinson ,
"eddyparkinson merged commit 1aa53b6 into audreyt:master 9 days ago"
it means that you already merged and  multisheet problem should be fixed in "https://ethercalc.org/" or not?
I can still reproduce bug in these steps:
1) create "https://ethercalc.org/=checkmulti"
2) add 2 more sheets 
3) rename all sheets "123" ; "234" ; "345"
4) reload page 
5) there left only last sheet "345"
6) checking "https://ethercalc.org/checkmulti"
7)	
    [empty]        | [empty]
    [empty]        | 123
/checkmulti.2	| [empty]
/checkmulti.3	| 345

**Comment by eddyparkinson** [comment]
@liudvikaris Only github code has been updated. There is not automated deploy to https://ethercalc.org/ audreyt will update it at some point in the next month or so I expect. If you are in a rush, send her a message.

**Comment by audreyt** [comment]
Yup. Released to NPM as `ethercalc@0.20190703.0`.

**Comment by liudvikaris** [comment]
@eddyparkinson @audreyt  Its sad, but the bug is still existing with installed ethercalc@0.20190703.0 and online version https://ethercalc.org/  

How to reproduce:
1. create new room (created https://ethercalc.org/=checkmulti12345)
2. add extra 2 more sheets 
3. rename all sheets (1 - 123; 2 - 456; 3 - 789)
4. reload room(webpage) 
5. there is still 3 sheets but names are (1 - Sheet1 ; 2 - Sheet2 ; 3 - 789)
6. Checking https://ethercalc.org/checkmulti12345
add pic 
firefox_ObyX8KN4oa

**Comment by khawarjatoi** [comment]
This bug is because of this [commit](https://github.com/audreyt/ethercalc/commit/0cdd4a02ccd7aee2810f21a95a5813bb921058ee).

**Comment by eddyparkinson** [comment]
Cause?
---

@khawarjatoi   Are you sure that commit is the cause. All it looks to do is add a line to the save file. 

e,g,  "copiedfrom:A1:B2" is added to the save file.

by

`copiedfrom:#copied-start:#copied-end\\n`

There looks to be an issue with renaming empty sheets. Look ok if sheets have values, but when sheets are empty it hits the bug. Can you test your version again, as described?

Workaround
---

@liudvikaris look to work if you add content and reload then rename. Not ideal but worked for me.

**Comment by liudvikaris** [comment]
@eddyparkinson 
I tried:
1) created new room
2) add content
3) reload page
4) rename Sheet to "123"
5) reload page
6) sheet name again "Sheet1"
7) again renamed sheet + add content
8) reload page and aswel sheet name become "Sheet1"

**Comment by eddyparkinson** [comment]
@liudvikaris agree - I get the same with your 8 step on ethercalc.org

But if I add a sheet, add content to both sheets, then rename sheets, all works as expected. Even after a reload. Strange. 

I will reopen the issue.

**Comment by khawarjatoi** [comment]
Yes @eddyparkinson, there is contradiction between [1aa53b6](https://github.com/audreyt/ethercalc/commit/1aa53b652dda39f13b643635a4e24cdb9dec6251) and @audreyt commit [0cdd4a0](https://github.com/audreyt/ethercalc/commit/0cdd4a02ccd7aee2810f21a95a5813bb921058ee).
2nd commit resolves sheet disappearing issue but as you have said there is still an sheet renaming issue.

**Comment by liudvikaris** [comment]
@eddyparkinson Thank you! , yes, your workaround is working. 
aswel this problem can be fixed in link without "="
like https://ethercalc.org/checkmulti12345

**Pull request merged**
