### PR TITLE
Filter extra blank line when restoring from audit file

### PR DESCRIPTION
**Pull request by atifaziz**
This PR addresses [an issue that was identified during the review](https://github.com/audreyt/ethercalc/pull/597#discussion_r174136544) from PR #597.

### CODE REVIEW

**Comment by eddyparkinson** [comment]
Please add a comment so I know it was tested.

**Comment by atifaziz** [comment]
@eddyparkinson This was already tested as part of PR #597. This PR is here because #597 was merged before that feedback could be integrated.

**Comment by atifaziz** [comment]
@eddyparkinson Any chance this can be merged soon?

**Comment by eddyparkinson** [comment]
@atifaziz been busy moving house - sorry for the slow merge.

**Pull request merged**
