### PR TITLE
Dependency upgrades

### PR DESCRIPTION
**Pull request by tpltnt**
Hi there,

I upgraded some dependencies to fix some of the vulnerabilities found via `npm audit`.

Cheers,
tpltnt

### CODE REVIEW

**Comment by eddyparkinson** [comment]
Did you test any of these? 

i.e.  zappajs needs major code changes before an upgrade is possible because the execution order changed.

**Comment by tpltnt** [comment]
I ran a test instance of ethercalc for a few hours and nothing "obvious" broke. I did not find a test-suite to run though.

**Comment by eddyparkinson** [comment]
@tpltnt true - lack of a test-suite is a problem. We don't have one. Probably a search through closed issues would give an idea of things that want testing, as bugs tend to have patterns. 

Not sure of the best way to move this forward. As these changes are not small isolated changes, so would bee good to have some more testing before merging. Have you any thoughts?

Re: zappajs - This is far from the latest version, looks like a bug fix release. I assume this is why it runs ok. Thanks for this.

**Comment by tpltnt** [comment]
I am terrible with JavaScript. I don't think I have the skillset and understanding of the codebase to write good test cases.

**Pull request closed without merging**
