### PR TITLE
New icon set (Galaxy from Libreoffice) and better style

### PR DESCRIPTION
**Pull request by FramaJosephK**
Hi,
I work for Framasoft, a french non profit NGO who wants to [degooglize the internet](https://degooglisons-internet.org/?l=en) and we propose and Ethercalc instance on framacalc.org since 2012.
 
I want to suggest you some cosmetic changes on the interface.
I explain it above because maybe you would not applied as they are. (I don't know very well how ethercalc is coded and I don't have a lot of time to investigate, so my contribution must be considered as a temporary "patch"). 

First, I've changed the icon set because many of our users don't understand what the buttons will do. The similarity between hide and remove row/column icons is very confusing for example (fortunately, there is the tooltip :) ). Others don't see the export "down arrow" button, I choose a floppy disk because it really means "save" the document (in spite of the fact that ethercalc already saves datas online).

Then, I've made some tweaks in the stylesheet static/makeup.css.
As style are applied inline by javascript, I have to make a lot of dirty stuffs like

- "!important" to give priority on stylesheet directives
- "#tableeditor td[id$="tab"][style*="#404040"]" or "#tableeditor > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)" in order to target the good element. It would be better targeted if there was some class in the DOM.

Some classes come from Twitter Bootstrap (we use it on all our sites) and are applied by jQuery calls in static/makeup.js. It was the easiest way to make a lot of little changes. There's a resize trigger to recalculate spreadsheet dimension at the end.

I saw that you are working on using bootstrap.min.css (there is a file in the static folder), so maybe you won't need the 164 first lines in makeup.css and these change could be added in the core of ethercalc later.

If you want to see the result, this is what you get with the stylesheet import in Firefox on ethercalc.org  
  
Then, when you applied classes from Bootstrap in the Firefox's scratchpad :  
  
And this is what you get with the Galaxy icon set :  

Of course we will apply these changes on Framacalc soon, so we share it with you before :)

### CODE REVIEW

**Comment by audreyt** [comment]
Lovely colors. Thanks for the contribution. Merged! 🌈

**Comment by ocdtrekkie** [comment]
That looks awesome. @audreyt Any chance of a Sandstorm update for this? The old insert row icons had me baffled literally two days ago.

**Comment by audreyt** [comment]
Sure. Let me look into that this weekend.

**Comment by ocdtrekkie** [comment]
Also worth asking: What's the license on the Galaxy set? Does the README need an update?

**Comment by FramaJosephK** [comment]
> What's the license on the Galaxy set?

I found this in the /usr/share/doc/libreoffice-style-galaxy/copyright file:  
> Copyright: Copyright 2000, 2010 Oracle and/or its affiliates.
>            Copyright (c) 2000, 2010 LibreOffice contributors and/or their affiliates.
> License: MPL-1.1 | GPL-3+ | LGPL-3+

**Comment by audreyt** [comment]
@ocdtrekkie Published to Sandstorm app market and on npm as 0.20160612.0

**Comment by ocdtrekkie** [comment]
Weird. I'm still seeing the old icons with the updated version.

**Comment by ocdtrekkie** [comment]
Nevermind, there we go.

**Comment by ldidry** [comment]
@audreyt The [npmjs version](https://www.npmjs.com/package/ethercalc) is still 0.20160501.1 :-(

**Comment by audreyt** [comment]
Published — the previous publish did not go through for some reason

**Pull request merged**
