### PR TITLE
Green theme #51B848 - beta

### PR DESCRIPTION
**Pull request by sank64**
Change few css properties, shorten few menu labels and replace icon menu files so as ethercalc looks green #51B848 and white, have a bigger type and can be displayed properly on smaller screens.

### CODE REVIEW

**Comment by sank64** [comment]
There are some CSS value changes I made originally to static/ethercalc.js which are not in this commit. As this scripts' header says: // Auto-generated from "make depends"; ALL CHANGES HERE WILL BE LOST! Can you tell me in which file to make these changes?

**Comment by audreyt** [comment]
Yes they are listed in the first 9 lines of `Makefile` .

**Comment by sank64** [comment]
Allright, now I have propagated the changes I made originally to ethercalc.js to the respective files. They are two main change: CSS color properties and removing few redundant menu buttons. The theme branch is ready to be tested.

**Comment by sank64** [comment]
Three buttons need to be taken out from the script.

1-Set clear move from
2-Move paste
3-Move insert

ethercalc-theme-beta-0001

**Comment by sank64** [comment]
I am stuck. I tried the change in socialcalcspreadsheetcontrol.js
 cf. "Simplify UI - part 3" but it doesn't affect anything. Maybe it's because I only use `npm i` to build the branch... as I don't have make on my server. Anyone can test it?

**Comment by audreyt** [comment]
Hmm. If someone can convert `Makefile` to npm scripts or `gulpfile` etc I'd happily take the pull request.

However what is your system? Is it a shared system preventing user-installed `make` binaries? (I think even Windows has `dmake.exe` or similar)

**Comment by sank64** [comment]
Some kind of tweaked linux. It's a NAS. I tried to patch it once but it went very cumbersome. I could switch to a docker version of ethercalc instead of using it natively but somehow I can't get it to work with my redis db.

**Comment by audreyt** [comment]
Well, try the docker version with no redis link... Namely https://hub.docker.com/r/audreyt/ethercalc/ which I just pushed an update to.

Without redis, EtherCalc will just use `dump.json` which you can mount from outside of the docker (or just make it ephemeral, shouldn't matter for development).

**Comment by sank64** [comment]
I see you only have latest tag so I get if I am using this docker file, I will get the master branch not the themes one?

**Comment by audreyt** [comment]
Yes but you can from within the docker do a git checkout to obtain the new ones and develop from within there. Something like:

```bash
docker run -it audreyt/ethercalc bash
cd ~
git clone -b themes https://github.com/audreyt/ethercalc.git
cd ethercalc
npm i
make
```

Before you quick the bash shell, you may want to use `docker commit` etc to save the state between runs.

**Comment by sank64** [comment]
Thanks for your explanation. I'll give it a try.

**Comment by sank64** [comment]
Do you have any tips? I ve been trying different fix from the web/docker man pages without any success.

**Comment by audreyt** [comment]
Did you miss the `cd ~` or just `cd` step ? That should move you to the `/home/ethercalc` directory and not the root directory. Or try `cd /tmp` before cloning.

**Comment by sank64** [comment]
I get after line 3:
Cloning into 'ethercalc'...
fatal: unable to access 'https://github.com/audreyt/ethercalc.git/': Could not resolve host: github.com
I have searched the web and it seems connected to DNS settings. But is it Dockers DNS og server's DNS? I will continue to search.

**Comment by audreyt** [comment]
It is Docker's DNS settings. Try replacing `github.com` with `192.30.252.129` and see if it helps.

**Comment by sank64** [comment]
Allright. It's my server again which is shipped without almost any admin flags for docker. I can't test the branch as I can't get npm to fetch any resources needed. It's just not a testing environement. I don't have setup a dedicated VM right now.

**Comment by audreyt** [comment]
OK, thanks for the report — let's continue at your convenience then :)

**Pull request merged**
