### PR TITLE
Fix broken multi sheet feature.

### PR DESCRIPTION
**Pull request by Prillan**
Makes the multi sheet mode work again!

### CODE REVIEW

**Comment by eddyparkinson** [comment]
thanks for the pull request. I will try to look at it later this week.

**Comment by newsiberian** [comment]
this changes doesn't fix multi sheet xlsx file importing bug for me. I've tested w/ two tabbed file

**Comment by Prillan** [comment]
> 
> 
> this changes doesn't fix multi sheet xlsx file importing bug for me. I've tested w/ two tabbed file

This only fixes an error introduced in c2cc1b45da880ba45f75ea1d34d72481dca0056d that made everything related to viewing/editing multiple sheets fail.

**Comment by newsiberian** [comment]
ok, I was thinking this is a fix of multi sheet file importing

**Pull request merged**
